ALTER TABLE cases ADD COLUMN IF NOT EXISTS noi_status TEXT DEFAULT 'DOCUMENTS_RECEIVED';

CREATE TYPE noi_status_enum AS ENUM (
    'DOCUMENTS_RECEIVED',
    'CHALLAN_GENERATED',
    'CHALLAN_PAID',
    'VERIFIED',
    'NOI_DROP_RECEIVED',
    'RECTIFY',
    'NOI_FILED',
    'ACKNOWLEDGED',
    'COMPLETED',
    'MISMATCH',
    'REJECTED'
);
